# Generated by Django 2.2.5 on 2020-08-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200805_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest',
            new_name='guests',
        ),
    ]
