# Generated by Django 2.2.5 on 2020-08-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200812_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
    ]
